name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout fe repository
        uses: actions/checkout@v4
        with:
          path: fe

      - name: Checkout interpreters repository
        uses: actions/checkout@v4
        with:
          repository: exercism/jiki-interpreters
          path: interpreters
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
          cache-dependency-path: fe/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: fe
        run: pnpm install --frozen-lockfile

      - name: Build application
        working-directory: fe
        run: pnpm run build

      - name: Install Puppeteer browser and dependencies
        run: |
          # Install Chrome browser for Puppeteer
          npx puppeteer browsers install chrome

          # Install required system dependencies (Ubuntu 24.04 compatible)
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libdrm2 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libxkbcommon0 \
            libxss1 \
            libgtk-3-0t64 \
            libgbm-dev \
            libatspi2.0-0 \
            libcups2 \
            libasound2t64

      - name: Run E2E tests
        working-directory: fe
        run: pnpm test:e2e
        env:
          HEADLESS: true
          CI: true

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots
          path: |
            fe/screenshots/
            fe/test-results/
          retention-days: 7
