name: TypeScript Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout fe repository
        uses: actions/checkout@v4
        with:
          path: fe

      - name: Checkout interpreters repository
        uses: actions/checkout@v4
        with:
          repository: exercism/jiki-interpreters
          path: interpreters
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
          cache-dependency-path: fe/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: fe
        run: pnpm install --frozen-lockfile

      - name: Run TypeScript type check
        working-directory: fe
        run: npx tsc --noEmit
