name: TypeScript Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout fe repository
        uses: actions/checkout@v4
        with:
          path: fe

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
          cache-dependency-path: fe/pnpm-lock.yaml

      - name: Setup SSH for interpreters repository
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.INTERPRETERS_DEPLOY_KEY }}

      - name: Checkout interpreters repository
        run: |
          git clone git@github.com:exercism/jiki-interpreters.git interpreters

      - name: Build interpreters package
        working-directory: interpreters
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Install fe dependencies
        working-directory: fe
        run: pnpm install --frozen-lockfile

      - name: Run TypeScript type check
        working-directory: fe
        run: npx tsc --noEmit
